/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppSalesRouteImport } from './routes/_authenticated/app.sales'
import { Route as AuthenticatedAppPurchasingRouteImport } from './routes/_authenticated/app.purchasing'
import { Route as AuthenticatedAppPosRouteImport } from './routes/_authenticated/app.pos'
import { Route as AuthenticatedAppManufacturingRouteImport } from './routes/_authenticated/app.manufacturing'
import { Route as AuthenticatedAppInventoryRouteImport } from './routes/_authenticated/app.inventory'
import { Route as AuthenticatedAppHrRouteImport } from './routes/_authenticated/app.hr'
import { Route as AuthenticatedAppCrmRouteImport } from './routes/_authenticated/app.crm'
import { Route as AuthenticatedAppCmsRouteImport } from './routes/_authenticated/app.cms'
import { Route as AuthenticatedAppAccountingRouteImport } from './routes/_authenticated/app.accounting'
import { Route as AuthenticatedAppUnitsIndexRouteImport } from './routes/_authenticated/app.units.index'
import { Route as AuthenticatedAppSalesIndexRouteImport } from './routes/_authenticated/app.sales.index'
import { Route as AuthenticatedAppPurchasingIndexRouteImport } from './routes/_authenticated/app.purchasing.index'
import { Route as AuthenticatedAppProductsIndexRouteImport } from './routes/_authenticated/app.products.index'
import { Route as AuthenticatedAppPosIndexRouteImport } from './routes/_authenticated/app.pos.index'
import { Route as AuthenticatedAppManufacturingIndexRouteImport } from './routes/_authenticated/app.manufacturing.index'
import { Route as AuthenticatedAppInventoryIndexRouteImport } from './routes/_authenticated/app.inventory.index'
import { Route as AuthenticatedAppHrIndexRouteImport } from './routes/_authenticated/app.hr.index'
import { Route as AuthenticatedAppCmsIndexRouteImport } from './routes/_authenticated/app.cms.index'
import { Route as AuthenticatedAppCategoriesIndexRouteImport } from './routes/_authenticated/app.categories.index'
import { Route as AuthenticatedAppAccountingIndexRouteImport } from './routes/_authenticated/app.accounting.index'
import { Route as AuthenticatedAppSalesInvoicesRouteImport } from './routes/_authenticated/app.sales.invoices'
import { Route as AuthenticatedAppSalesCustomersRouteImport } from './routes/_authenticated/app.sales.customers'
import { Route as AuthenticatedAppPurchasingSuppliersRouteImport } from './routes/_authenticated/app.purchasing.suppliers'
import { Route as AuthenticatedAppPosHistoryRouteImport } from './routes/_authenticated/app.pos.history'
import { Route as AuthenticatedAppManufacturingWoRouteImport } from './routes/_authenticated/app.manufacturing.wo'
import { Route as AuthenticatedAppManufacturingMrpRouteImport } from './routes/_authenticated/app.manufacturing.mrp'
import { Route as AuthenticatedAppManufacturingBomRouteImport } from './routes/_authenticated/app.manufacturing.bom'
import { Route as AuthenticatedAppInventoryOpnameRouteImport } from './routes/_authenticated/app.inventory.opname'
import { Route as AuthenticatedAppInventoryMovementsRouteImport } from './routes/_authenticated/app.inventory.movements'
import { Route as AuthenticatedAppHrPayrollRouteImport } from './routes/_authenticated/app.hr.payroll'
import { Route as AuthenticatedAppHrLeaveRouteImport } from './routes/_authenticated/app.hr.leave'
import { Route as AuthenticatedAppHrEmployeesRouteImport } from './routes/_authenticated/app.hr.employees'
import { Route as AuthenticatedAppHrDepartmentsRouteImport } from './routes/_authenticated/app.hr.departments'
import { Route as AuthenticatedAppHrAttendanceRouteImport } from './routes/_authenticated/app.hr.attendance'
import { Route as AuthenticatedAppCrmOpportunitiesRouteImport } from './routes/_authenticated/app.crm.opportunities'
import { Route as AuthenticatedAppCrmLeadsRouteImport } from './routes/_authenticated/app.crm.leads'
import { Route as AuthenticatedAppCrmCustomersRouteImport } from './routes/_authenticated/app.crm.customers'
import { Route as AuthenticatedAppCrmActivitiesRouteImport } from './routes/_authenticated/app.crm.activities'
import { Route as AuthenticatedAppCmsPostsRouteImport } from './routes/_authenticated/app.cms.posts'
import { Route as AuthenticatedAppAccountingReportsRouteImport } from './routes/_authenticated/app.accounting.reports'
import { Route as AuthenticatedAppAccountingJournalsRouteImport } from './routes/_authenticated/app.accounting.journals'
import { Route as AuthenticatedAppSalesOrdersSoIdRouteImport } from './routes/_authenticated/app.sales.orders.$soId'
import { Route as AuthenticatedAppPurchasingOrdersPoIdRouteImport } from './routes/_authenticated/app.purchasing.orders.$poId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppSalesRoute = AuthenticatedAppSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPurchasingRoute =
  AuthenticatedAppPurchasingRouteImport.update({
    id: '/purchasing',
    path: '/purchasing',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPosRoute = AuthenticatedAppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppManufacturingRoute =
  AuthenticatedAppManufacturingRouteImport.update({
    id: '/manufacturing',
    path: '/manufacturing',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppInventoryRoute =
  AuthenticatedAppInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHrRoute = AuthenticatedAppHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCrmRoute = AuthenticatedAppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCmsRoute = AuthenticatedAppCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppAccountingRoute =
  AuthenticatedAppAccountingRouteImport.update({
    id: '/accounting',
    path: '/accounting',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppUnitsIndexRoute =
  AuthenticatedAppUnitsIndexRouteImport.update({
    id: '/units/',
    path: '/units/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppSalesIndexRoute =
  AuthenticatedAppSalesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppSalesRoute,
  } as any)
const AuthenticatedAppPurchasingIndexRoute =
  AuthenticatedAppPurchasingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppPurchasingRoute,
  } as any)
const AuthenticatedAppProductsIndexRoute =
  AuthenticatedAppProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppPosIndexRoute =
  AuthenticatedAppPosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppPosRoute,
  } as any)
const AuthenticatedAppManufacturingIndexRoute =
  AuthenticatedAppManufacturingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppManufacturingRoute,
  } as any)
const AuthenticatedAppInventoryIndexRoute =
  AuthenticatedAppInventoryIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppInventoryRoute,
  } as any)
const AuthenticatedAppHrIndexRoute = AuthenticatedAppHrIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppHrRoute,
} as any)
const AuthenticatedAppCmsIndexRoute =
  AuthenticatedAppCmsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppCmsRoute,
  } as any)
const AuthenticatedAppCategoriesIndexRoute =
  AuthenticatedAppCategoriesIndexRouteImport.update({
    id: '/categories/',
    path: '/categories/',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAccountingIndexRoute =
  AuthenticatedAppAccountingIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppAccountingRoute,
  } as any)
const AuthenticatedAppSalesInvoicesRoute =
  AuthenticatedAppSalesInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAppSalesRoute,
  } as any)
const AuthenticatedAppSalesCustomersRoute =
  AuthenticatedAppSalesCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAppSalesRoute,
  } as any)
const AuthenticatedAppPurchasingSuppliersRoute =
  AuthenticatedAppPurchasingSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedAppPurchasingRoute,
  } as any)
const AuthenticatedAppPosHistoryRoute =
  AuthenticatedAppPosHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedAppPosRoute,
  } as any)
const AuthenticatedAppManufacturingWoRoute =
  AuthenticatedAppManufacturingWoRouteImport.update({
    id: '/wo',
    path: '/wo',
    getParentRoute: () => AuthenticatedAppManufacturingRoute,
  } as any)
const AuthenticatedAppManufacturingMrpRoute =
  AuthenticatedAppManufacturingMrpRouteImport.update({
    id: '/mrp',
    path: '/mrp',
    getParentRoute: () => AuthenticatedAppManufacturingRoute,
  } as any)
const AuthenticatedAppManufacturingBomRoute =
  AuthenticatedAppManufacturingBomRouteImport.update({
    id: '/bom',
    path: '/bom',
    getParentRoute: () => AuthenticatedAppManufacturingRoute,
  } as any)
const AuthenticatedAppInventoryOpnameRoute =
  AuthenticatedAppInventoryOpnameRouteImport.update({
    id: '/opname',
    path: '/opname',
    getParentRoute: () => AuthenticatedAppInventoryRoute,
  } as any)
const AuthenticatedAppInventoryMovementsRoute =
  AuthenticatedAppInventoryMovementsRouteImport.update({
    id: '/movements',
    path: '/movements',
    getParentRoute: () => AuthenticatedAppInventoryRoute,
  } as any)
const AuthenticatedAppHrPayrollRoute =
  AuthenticatedAppHrPayrollRouteImport.update({
    id: '/payroll',
    path: '/payroll',
    getParentRoute: () => AuthenticatedAppHrRoute,
  } as any)
const AuthenticatedAppHrLeaveRoute = AuthenticatedAppHrLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => AuthenticatedAppHrRoute,
} as any)
const AuthenticatedAppHrEmployeesRoute =
  AuthenticatedAppHrEmployeesRouteImport.update({
    id: '/employees',
    path: '/employees',
    getParentRoute: () => AuthenticatedAppHrRoute,
  } as any)
const AuthenticatedAppHrDepartmentsRoute =
  AuthenticatedAppHrDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedAppHrRoute,
  } as any)
const AuthenticatedAppHrAttendanceRoute =
  AuthenticatedAppHrAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => AuthenticatedAppHrRoute,
  } as any)
const AuthenticatedAppCrmOpportunitiesRoute =
  AuthenticatedAppCrmOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedAppCrmRoute,
  } as any)
const AuthenticatedAppCrmLeadsRoute =
  AuthenticatedAppCrmLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedAppCrmRoute,
  } as any)
const AuthenticatedAppCrmCustomersRoute =
  AuthenticatedAppCrmCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAppCrmRoute,
  } as any)
const AuthenticatedAppCrmActivitiesRoute =
  AuthenticatedAppCrmActivitiesRouteImport.update({
    id: '/activities',
    path: '/activities',
    getParentRoute: () => AuthenticatedAppCrmRoute,
  } as any)
const AuthenticatedAppCmsPostsRoute =
  AuthenticatedAppCmsPostsRouteImport.update({
    id: '/posts',
    path: '/posts',
    getParentRoute: () => AuthenticatedAppCmsRoute,
  } as any)
const AuthenticatedAppAccountingReportsRoute =
  AuthenticatedAppAccountingReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAppAccountingRoute,
  } as any)
const AuthenticatedAppAccountingJournalsRoute =
  AuthenticatedAppAccountingJournalsRouteImport.update({
    id: '/journals',
    path: '/journals',
    getParentRoute: () => AuthenticatedAppAccountingRoute,
  } as any)
const AuthenticatedAppSalesOrdersSoIdRoute =
  AuthenticatedAppSalesOrdersSoIdRouteImport.update({
    id: '/orders/$soId',
    path: '/orders/$soId',
    getParentRoute: () => AuthenticatedAppSalesRoute,
  } as any)
const AuthenticatedAppPurchasingOrdersPoIdRoute =
  AuthenticatedAppPurchasingOrdersPoIdRouteImport.update({
    id: '/orders/$poId',
    path: '/orders/$poId',
    getParentRoute: () => AuthenticatedAppPurchasingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/app/accounting': typeof AuthenticatedAppAccountingRouteWithChildren
  '/app/cms': typeof AuthenticatedAppCmsRouteWithChildren
  '/app/crm': typeof AuthenticatedAppCrmRouteWithChildren
  '/app/hr': typeof AuthenticatedAppHrRouteWithChildren
  '/app/inventory': typeof AuthenticatedAppInventoryRouteWithChildren
  '/app/manufacturing': typeof AuthenticatedAppManufacturingRouteWithChildren
  '/app/pos': typeof AuthenticatedAppPosRouteWithChildren
  '/app/purchasing': typeof AuthenticatedAppPurchasingRouteWithChildren
  '/app/sales': typeof AuthenticatedAppSalesRouteWithChildren
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/accounting/journals': typeof AuthenticatedAppAccountingJournalsRoute
  '/app/accounting/reports': typeof AuthenticatedAppAccountingReportsRoute
  '/app/cms/posts': typeof AuthenticatedAppCmsPostsRoute
  '/app/crm/activities': typeof AuthenticatedAppCrmActivitiesRoute
  '/app/crm/customers': typeof AuthenticatedAppCrmCustomersRoute
  '/app/crm/leads': typeof AuthenticatedAppCrmLeadsRoute
  '/app/crm/opportunities': typeof AuthenticatedAppCrmOpportunitiesRoute
  '/app/hr/attendance': typeof AuthenticatedAppHrAttendanceRoute
  '/app/hr/departments': typeof AuthenticatedAppHrDepartmentsRoute
  '/app/hr/employees': typeof AuthenticatedAppHrEmployeesRoute
  '/app/hr/leave': typeof AuthenticatedAppHrLeaveRoute
  '/app/hr/payroll': typeof AuthenticatedAppHrPayrollRoute
  '/app/inventory/movements': typeof AuthenticatedAppInventoryMovementsRoute
  '/app/inventory/opname': typeof AuthenticatedAppInventoryOpnameRoute
  '/app/manufacturing/bom': typeof AuthenticatedAppManufacturingBomRoute
  '/app/manufacturing/mrp': typeof AuthenticatedAppManufacturingMrpRoute
  '/app/manufacturing/wo': typeof AuthenticatedAppManufacturingWoRoute
  '/app/pos/history': typeof AuthenticatedAppPosHistoryRoute
  '/app/purchasing/suppliers': typeof AuthenticatedAppPurchasingSuppliersRoute
  '/app/sales/customers': typeof AuthenticatedAppSalesCustomersRoute
  '/app/sales/invoices': typeof AuthenticatedAppSalesInvoicesRoute
  '/app/accounting/': typeof AuthenticatedAppAccountingIndexRoute
  '/app/categories/': typeof AuthenticatedAppCategoriesIndexRoute
  '/app/cms/': typeof AuthenticatedAppCmsIndexRoute
  '/app/hr/': typeof AuthenticatedAppHrIndexRoute
  '/app/inventory/': typeof AuthenticatedAppInventoryIndexRoute
  '/app/manufacturing/': typeof AuthenticatedAppManufacturingIndexRoute
  '/app/pos/': typeof AuthenticatedAppPosIndexRoute
  '/app/products/': typeof AuthenticatedAppProductsIndexRoute
  '/app/purchasing/': typeof AuthenticatedAppPurchasingIndexRoute
  '/app/sales/': typeof AuthenticatedAppSalesIndexRoute
  '/app/units/': typeof AuthenticatedAppUnitsIndexRoute
  '/app/purchasing/orders/$poId': typeof AuthenticatedAppPurchasingOrdersPoIdRoute
  '/app/sales/orders/$soId': typeof AuthenticatedAppSalesOrdersSoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
  '/app/crm': typeof AuthenticatedAppCrmRouteWithChildren
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/accounting/journals': typeof AuthenticatedAppAccountingJournalsRoute
  '/app/accounting/reports': typeof AuthenticatedAppAccountingReportsRoute
  '/app/cms/posts': typeof AuthenticatedAppCmsPostsRoute
  '/app/crm/activities': typeof AuthenticatedAppCrmActivitiesRoute
  '/app/crm/customers': typeof AuthenticatedAppCrmCustomersRoute
  '/app/crm/leads': typeof AuthenticatedAppCrmLeadsRoute
  '/app/crm/opportunities': typeof AuthenticatedAppCrmOpportunitiesRoute
  '/app/hr/attendance': typeof AuthenticatedAppHrAttendanceRoute
  '/app/hr/departments': typeof AuthenticatedAppHrDepartmentsRoute
  '/app/hr/employees': typeof AuthenticatedAppHrEmployeesRoute
  '/app/hr/leave': typeof AuthenticatedAppHrLeaveRoute
  '/app/hr/payroll': typeof AuthenticatedAppHrPayrollRoute
  '/app/inventory/movements': typeof AuthenticatedAppInventoryMovementsRoute
  '/app/inventory/opname': typeof AuthenticatedAppInventoryOpnameRoute
  '/app/manufacturing/bom': typeof AuthenticatedAppManufacturingBomRoute
  '/app/manufacturing/mrp': typeof AuthenticatedAppManufacturingMrpRoute
  '/app/manufacturing/wo': typeof AuthenticatedAppManufacturingWoRoute
  '/app/pos/history': typeof AuthenticatedAppPosHistoryRoute
  '/app/purchasing/suppliers': typeof AuthenticatedAppPurchasingSuppliersRoute
  '/app/sales/customers': typeof AuthenticatedAppSalesCustomersRoute
  '/app/sales/invoices': typeof AuthenticatedAppSalesInvoicesRoute
  '/app/accounting': typeof AuthenticatedAppAccountingIndexRoute
  '/app/categories': typeof AuthenticatedAppCategoriesIndexRoute
  '/app/cms': typeof AuthenticatedAppCmsIndexRoute
  '/app/hr': typeof AuthenticatedAppHrIndexRoute
  '/app/inventory': typeof AuthenticatedAppInventoryIndexRoute
  '/app/manufacturing': typeof AuthenticatedAppManufacturingIndexRoute
  '/app/pos': typeof AuthenticatedAppPosIndexRoute
  '/app/products': typeof AuthenticatedAppProductsIndexRoute
  '/app/purchasing': typeof AuthenticatedAppPurchasingIndexRoute
  '/app/sales': typeof AuthenticatedAppSalesIndexRoute
  '/app/units': typeof AuthenticatedAppUnitsIndexRoute
  '/app/purchasing/orders/$poId': typeof AuthenticatedAppPurchasingOrdersPoIdRoute
  '/app/sales/orders/$soId': typeof AuthenticatedAppSalesOrdersSoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/app/accounting': typeof AuthenticatedAppAccountingRouteWithChildren
  '/_authenticated/app/cms': typeof AuthenticatedAppCmsRouteWithChildren
  '/_authenticated/app/crm': typeof AuthenticatedAppCrmRouteWithChildren
  '/_authenticated/app/hr': typeof AuthenticatedAppHrRouteWithChildren
  '/_authenticated/app/inventory': typeof AuthenticatedAppInventoryRouteWithChildren
  '/_authenticated/app/manufacturing': typeof AuthenticatedAppManufacturingRouteWithChildren
  '/_authenticated/app/pos': typeof AuthenticatedAppPosRouteWithChildren
  '/_authenticated/app/purchasing': typeof AuthenticatedAppPurchasingRouteWithChildren
  '/_authenticated/app/sales': typeof AuthenticatedAppSalesRouteWithChildren
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/accounting/journals': typeof AuthenticatedAppAccountingJournalsRoute
  '/_authenticated/app/accounting/reports': typeof AuthenticatedAppAccountingReportsRoute
  '/_authenticated/app/cms/posts': typeof AuthenticatedAppCmsPostsRoute
  '/_authenticated/app/crm/activities': typeof AuthenticatedAppCrmActivitiesRoute
  '/_authenticated/app/crm/customers': typeof AuthenticatedAppCrmCustomersRoute
  '/_authenticated/app/crm/leads': typeof AuthenticatedAppCrmLeadsRoute
  '/_authenticated/app/crm/opportunities': typeof AuthenticatedAppCrmOpportunitiesRoute
  '/_authenticated/app/hr/attendance': typeof AuthenticatedAppHrAttendanceRoute
  '/_authenticated/app/hr/departments': typeof AuthenticatedAppHrDepartmentsRoute
  '/_authenticated/app/hr/employees': typeof AuthenticatedAppHrEmployeesRoute
  '/_authenticated/app/hr/leave': typeof AuthenticatedAppHrLeaveRoute
  '/_authenticated/app/hr/payroll': typeof AuthenticatedAppHrPayrollRoute
  '/_authenticated/app/inventory/movements': typeof AuthenticatedAppInventoryMovementsRoute
  '/_authenticated/app/inventory/opname': typeof AuthenticatedAppInventoryOpnameRoute
  '/_authenticated/app/manufacturing/bom': typeof AuthenticatedAppManufacturingBomRoute
  '/_authenticated/app/manufacturing/mrp': typeof AuthenticatedAppManufacturingMrpRoute
  '/_authenticated/app/manufacturing/wo': typeof AuthenticatedAppManufacturingWoRoute
  '/_authenticated/app/pos/history': typeof AuthenticatedAppPosHistoryRoute
  '/_authenticated/app/purchasing/suppliers': typeof AuthenticatedAppPurchasingSuppliersRoute
  '/_authenticated/app/sales/customers': typeof AuthenticatedAppSalesCustomersRoute
  '/_authenticated/app/sales/invoices': typeof AuthenticatedAppSalesInvoicesRoute
  '/_authenticated/app/accounting/': typeof AuthenticatedAppAccountingIndexRoute
  '/_authenticated/app/categories/': typeof AuthenticatedAppCategoriesIndexRoute
  '/_authenticated/app/cms/': typeof AuthenticatedAppCmsIndexRoute
  '/_authenticated/app/hr/': typeof AuthenticatedAppHrIndexRoute
  '/_authenticated/app/inventory/': typeof AuthenticatedAppInventoryIndexRoute
  '/_authenticated/app/manufacturing/': typeof AuthenticatedAppManufacturingIndexRoute
  '/_authenticated/app/pos/': typeof AuthenticatedAppPosIndexRoute
  '/_authenticated/app/products/': typeof AuthenticatedAppProductsIndexRoute
  '/_authenticated/app/purchasing/': typeof AuthenticatedAppPurchasingIndexRoute
  '/_authenticated/app/sales/': typeof AuthenticatedAppSalesIndexRoute
  '/_authenticated/app/units/': typeof AuthenticatedAppUnitsIndexRoute
  '/_authenticated/app/purchasing/orders/$poId': typeof AuthenticatedAppPurchasingOrdersPoIdRoute
  '/_authenticated/app/sales/orders/$soId': typeof AuthenticatedAppSalesOrdersSoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/blog/$slug'
    | '/blog/'
    | '/app/accounting'
    | '/app/cms'
    | '/app/crm'
    | '/app/hr'
    | '/app/inventory'
    | '/app/manufacturing'
    | '/app/pos'
    | '/app/purchasing'
    | '/app/sales'
    | '/app/'
    | '/app/accounting/journals'
    | '/app/accounting/reports'
    | '/app/cms/posts'
    | '/app/crm/activities'
    | '/app/crm/customers'
    | '/app/crm/leads'
    | '/app/crm/opportunities'
    | '/app/hr/attendance'
    | '/app/hr/departments'
    | '/app/hr/employees'
    | '/app/hr/leave'
    | '/app/hr/payroll'
    | '/app/inventory/movements'
    | '/app/inventory/opname'
    | '/app/manufacturing/bom'
    | '/app/manufacturing/mrp'
    | '/app/manufacturing/wo'
    | '/app/pos/history'
    | '/app/purchasing/suppliers'
    | '/app/sales/customers'
    | '/app/sales/invoices'
    | '/app/accounting/'
    | '/app/categories/'
    | '/app/cms/'
    | '/app/hr/'
    | '/app/inventory/'
    | '/app/manufacturing/'
    | '/app/pos/'
    | '/app/products/'
    | '/app/purchasing/'
    | '/app/sales/'
    | '/app/units/'
    | '/app/purchasing/orders/$poId'
    | '/app/sales/orders/$soId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog/$slug'
    | '/blog'
    | '/app/crm'
    | '/app'
    | '/app/accounting/journals'
    | '/app/accounting/reports'
    | '/app/cms/posts'
    | '/app/crm/activities'
    | '/app/crm/customers'
    | '/app/crm/leads'
    | '/app/crm/opportunities'
    | '/app/hr/attendance'
    | '/app/hr/departments'
    | '/app/hr/employees'
    | '/app/hr/leave'
    | '/app/hr/payroll'
    | '/app/inventory/movements'
    | '/app/inventory/opname'
    | '/app/manufacturing/bom'
    | '/app/manufacturing/mrp'
    | '/app/manufacturing/wo'
    | '/app/pos/history'
    | '/app/purchasing/suppliers'
    | '/app/sales/customers'
    | '/app/sales/invoices'
    | '/app/accounting'
    | '/app/categories'
    | '/app/cms'
    | '/app/hr'
    | '/app/inventory'
    | '/app/manufacturing'
    | '/app/pos'
    | '/app/products'
    | '/app/purchasing'
    | '/app/sales'
    | '/app/units'
    | '/app/purchasing/orders/$poId'
    | '/app/sales/orders/$soId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/blog/$slug'
    | '/blog/'
    | '/_authenticated/app/accounting'
    | '/_authenticated/app/cms'
    | '/_authenticated/app/crm'
    | '/_authenticated/app/hr'
    | '/_authenticated/app/inventory'
    | '/_authenticated/app/manufacturing'
    | '/_authenticated/app/pos'
    | '/_authenticated/app/purchasing'
    | '/_authenticated/app/sales'
    | '/_authenticated/app/'
    | '/_authenticated/app/accounting/journals'
    | '/_authenticated/app/accounting/reports'
    | '/_authenticated/app/cms/posts'
    | '/_authenticated/app/crm/activities'
    | '/_authenticated/app/crm/customers'
    | '/_authenticated/app/crm/leads'
    | '/_authenticated/app/crm/opportunities'
    | '/_authenticated/app/hr/attendance'
    | '/_authenticated/app/hr/departments'
    | '/_authenticated/app/hr/employees'
    | '/_authenticated/app/hr/leave'
    | '/_authenticated/app/hr/payroll'
    | '/_authenticated/app/inventory/movements'
    | '/_authenticated/app/inventory/opname'
    | '/_authenticated/app/manufacturing/bom'
    | '/_authenticated/app/manufacturing/mrp'
    | '/_authenticated/app/manufacturing/wo'
    | '/_authenticated/app/pos/history'
    | '/_authenticated/app/purchasing/suppliers'
    | '/_authenticated/app/sales/customers'
    | '/_authenticated/app/sales/invoices'
    | '/_authenticated/app/accounting/'
    | '/_authenticated/app/categories/'
    | '/_authenticated/app/cms/'
    | '/_authenticated/app/hr/'
    | '/_authenticated/app/inventory/'
    | '/_authenticated/app/manufacturing/'
    | '/_authenticated/app/pos/'
    | '/_authenticated/app/products/'
    | '/_authenticated/app/purchasing/'
    | '/_authenticated/app/sales/'
    | '/_authenticated/app/units/'
    | '/_authenticated/app/purchasing/orders/$poId'
    | '/_authenticated/app/sales/orders/$soId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sales': {
      id: '/_authenticated/app/sales'
      path: '/sales'
      fullPath: '/app/sales'
      preLoaderRoute: typeof AuthenticatedAppSalesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/purchasing': {
      id: '/_authenticated/app/purchasing'
      path: '/purchasing'
      fullPath: '/app/purchasing'
      preLoaderRoute: typeof AuthenticatedAppPurchasingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pos': {
      id: '/_authenticated/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AuthenticatedAppPosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/manufacturing': {
      id: '/_authenticated/app/manufacturing'
      path: '/manufacturing'
      fullPath: '/app/manufacturing'
      preLoaderRoute: typeof AuthenticatedAppManufacturingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/inventory': {
      id: '/_authenticated/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AuthenticatedAppInventoryRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/hr': {
      id: '/_authenticated/app/hr'
      path: '/hr'
      fullPath: '/app/hr'
      preLoaderRoute: typeof AuthenticatedAppHrRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/crm': {
      id: '/_authenticated/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AuthenticatedAppCrmRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cms': {
      id: '/_authenticated/app/cms'
      path: '/cms'
      fullPath: '/app/cms'
      preLoaderRoute: typeof AuthenticatedAppCmsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/accounting': {
      id: '/_authenticated/app/accounting'
      path: '/accounting'
      fullPath: '/app/accounting'
      preLoaderRoute: typeof AuthenticatedAppAccountingRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/units/': {
      id: '/_authenticated/app/units/'
      path: '/units'
      fullPath: '/app/units/'
      preLoaderRoute: typeof AuthenticatedAppUnitsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/sales/': {
      id: '/_authenticated/app/sales/'
      path: '/'
      fullPath: '/app/sales/'
      preLoaderRoute: typeof AuthenticatedAppSalesIndexRouteImport
      parentRoute: typeof AuthenticatedAppSalesRoute
    }
    '/_authenticated/app/purchasing/': {
      id: '/_authenticated/app/purchasing/'
      path: '/'
      fullPath: '/app/purchasing/'
      preLoaderRoute: typeof AuthenticatedAppPurchasingIndexRouteImport
      parentRoute: typeof AuthenticatedAppPurchasingRoute
    }
    '/_authenticated/app/products/': {
      id: '/_authenticated/app/products/'
      path: '/products'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AuthenticatedAppProductsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pos/': {
      id: '/_authenticated/app/pos/'
      path: '/'
      fullPath: '/app/pos/'
      preLoaderRoute: typeof AuthenticatedAppPosIndexRouteImport
      parentRoute: typeof AuthenticatedAppPosRoute
    }
    '/_authenticated/app/manufacturing/': {
      id: '/_authenticated/app/manufacturing/'
      path: '/'
      fullPath: '/app/manufacturing/'
      preLoaderRoute: typeof AuthenticatedAppManufacturingIndexRouteImport
      parentRoute: typeof AuthenticatedAppManufacturingRoute
    }
    '/_authenticated/app/inventory/': {
      id: '/_authenticated/app/inventory/'
      path: '/'
      fullPath: '/app/inventory/'
      preLoaderRoute: typeof AuthenticatedAppInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedAppInventoryRoute
    }
    '/_authenticated/app/hr/': {
      id: '/_authenticated/app/hr/'
      path: '/'
      fullPath: '/app/hr/'
      preLoaderRoute: typeof AuthenticatedAppHrIndexRouteImport
      parentRoute: typeof AuthenticatedAppHrRoute
    }
    '/_authenticated/app/cms/': {
      id: '/_authenticated/app/cms/'
      path: '/'
      fullPath: '/app/cms/'
      preLoaderRoute: typeof AuthenticatedAppCmsIndexRouteImport
      parentRoute: typeof AuthenticatedAppCmsRoute
    }
    '/_authenticated/app/categories/': {
      id: '/_authenticated/app/categories/'
      path: '/categories'
      fullPath: '/app/categories/'
      preLoaderRoute: typeof AuthenticatedAppCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/accounting/': {
      id: '/_authenticated/app/accounting/'
      path: '/'
      fullPath: '/app/accounting/'
      preLoaderRoute: typeof AuthenticatedAppAccountingIndexRouteImport
      parentRoute: typeof AuthenticatedAppAccountingRoute
    }
    '/_authenticated/app/sales/invoices': {
      id: '/_authenticated/app/sales/invoices'
      path: '/invoices'
      fullPath: '/app/sales/invoices'
      preLoaderRoute: typeof AuthenticatedAppSalesInvoicesRouteImport
      parentRoute: typeof AuthenticatedAppSalesRoute
    }
    '/_authenticated/app/sales/customers': {
      id: '/_authenticated/app/sales/customers'
      path: '/customers'
      fullPath: '/app/sales/customers'
      preLoaderRoute: typeof AuthenticatedAppSalesCustomersRouteImport
      parentRoute: typeof AuthenticatedAppSalesRoute
    }
    '/_authenticated/app/purchasing/suppliers': {
      id: '/_authenticated/app/purchasing/suppliers'
      path: '/suppliers'
      fullPath: '/app/purchasing/suppliers'
      preLoaderRoute: typeof AuthenticatedAppPurchasingSuppliersRouteImport
      parentRoute: typeof AuthenticatedAppPurchasingRoute
    }
    '/_authenticated/app/pos/history': {
      id: '/_authenticated/app/pos/history'
      path: '/history'
      fullPath: '/app/pos/history'
      preLoaderRoute: typeof AuthenticatedAppPosHistoryRouteImport
      parentRoute: typeof AuthenticatedAppPosRoute
    }
    '/_authenticated/app/manufacturing/wo': {
      id: '/_authenticated/app/manufacturing/wo'
      path: '/wo'
      fullPath: '/app/manufacturing/wo'
      preLoaderRoute: typeof AuthenticatedAppManufacturingWoRouteImport
      parentRoute: typeof AuthenticatedAppManufacturingRoute
    }
    '/_authenticated/app/manufacturing/mrp': {
      id: '/_authenticated/app/manufacturing/mrp'
      path: '/mrp'
      fullPath: '/app/manufacturing/mrp'
      preLoaderRoute: typeof AuthenticatedAppManufacturingMrpRouteImport
      parentRoute: typeof AuthenticatedAppManufacturingRoute
    }
    '/_authenticated/app/manufacturing/bom': {
      id: '/_authenticated/app/manufacturing/bom'
      path: '/bom'
      fullPath: '/app/manufacturing/bom'
      preLoaderRoute: typeof AuthenticatedAppManufacturingBomRouteImport
      parentRoute: typeof AuthenticatedAppManufacturingRoute
    }
    '/_authenticated/app/inventory/opname': {
      id: '/_authenticated/app/inventory/opname'
      path: '/opname'
      fullPath: '/app/inventory/opname'
      preLoaderRoute: typeof AuthenticatedAppInventoryOpnameRouteImport
      parentRoute: typeof AuthenticatedAppInventoryRoute
    }
    '/_authenticated/app/inventory/movements': {
      id: '/_authenticated/app/inventory/movements'
      path: '/movements'
      fullPath: '/app/inventory/movements'
      preLoaderRoute: typeof AuthenticatedAppInventoryMovementsRouteImport
      parentRoute: typeof AuthenticatedAppInventoryRoute
    }
    '/_authenticated/app/hr/payroll': {
      id: '/_authenticated/app/hr/payroll'
      path: '/payroll'
      fullPath: '/app/hr/payroll'
      preLoaderRoute: typeof AuthenticatedAppHrPayrollRouteImport
      parentRoute: typeof AuthenticatedAppHrRoute
    }
    '/_authenticated/app/hr/leave': {
      id: '/_authenticated/app/hr/leave'
      path: '/leave'
      fullPath: '/app/hr/leave'
      preLoaderRoute: typeof AuthenticatedAppHrLeaveRouteImport
      parentRoute: typeof AuthenticatedAppHrRoute
    }
    '/_authenticated/app/hr/employees': {
      id: '/_authenticated/app/hr/employees'
      path: '/employees'
      fullPath: '/app/hr/employees'
      preLoaderRoute: typeof AuthenticatedAppHrEmployeesRouteImport
      parentRoute: typeof AuthenticatedAppHrRoute
    }
    '/_authenticated/app/hr/departments': {
      id: '/_authenticated/app/hr/departments'
      path: '/departments'
      fullPath: '/app/hr/departments'
      preLoaderRoute: typeof AuthenticatedAppHrDepartmentsRouteImport
      parentRoute: typeof AuthenticatedAppHrRoute
    }
    '/_authenticated/app/hr/attendance': {
      id: '/_authenticated/app/hr/attendance'
      path: '/attendance'
      fullPath: '/app/hr/attendance'
      preLoaderRoute: typeof AuthenticatedAppHrAttendanceRouteImport
      parentRoute: typeof AuthenticatedAppHrRoute
    }
    '/_authenticated/app/crm/opportunities': {
      id: '/_authenticated/app/crm/opportunities'
      path: '/opportunities'
      fullPath: '/app/crm/opportunities'
      preLoaderRoute: typeof AuthenticatedAppCrmOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedAppCrmRoute
    }
    '/_authenticated/app/crm/leads': {
      id: '/_authenticated/app/crm/leads'
      path: '/leads'
      fullPath: '/app/crm/leads'
      preLoaderRoute: typeof AuthenticatedAppCrmLeadsRouteImport
      parentRoute: typeof AuthenticatedAppCrmRoute
    }
    '/_authenticated/app/crm/customers': {
      id: '/_authenticated/app/crm/customers'
      path: '/customers'
      fullPath: '/app/crm/customers'
      preLoaderRoute: typeof AuthenticatedAppCrmCustomersRouteImport
      parentRoute: typeof AuthenticatedAppCrmRoute
    }
    '/_authenticated/app/crm/activities': {
      id: '/_authenticated/app/crm/activities'
      path: '/activities'
      fullPath: '/app/crm/activities'
      preLoaderRoute: typeof AuthenticatedAppCrmActivitiesRouteImport
      parentRoute: typeof AuthenticatedAppCrmRoute
    }
    '/_authenticated/app/cms/posts': {
      id: '/_authenticated/app/cms/posts'
      path: '/posts'
      fullPath: '/app/cms/posts'
      preLoaderRoute: typeof AuthenticatedAppCmsPostsRouteImport
      parentRoute: typeof AuthenticatedAppCmsRoute
    }
    '/_authenticated/app/accounting/reports': {
      id: '/_authenticated/app/accounting/reports'
      path: '/reports'
      fullPath: '/app/accounting/reports'
      preLoaderRoute: typeof AuthenticatedAppAccountingReportsRouteImport
      parentRoute: typeof AuthenticatedAppAccountingRoute
    }
    '/_authenticated/app/accounting/journals': {
      id: '/_authenticated/app/accounting/journals'
      path: '/journals'
      fullPath: '/app/accounting/journals'
      preLoaderRoute: typeof AuthenticatedAppAccountingJournalsRouteImport
      parentRoute: typeof AuthenticatedAppAccountingRoute
    }
    '/_authenticated/app/sales/orders/$soId': {
      id: '/_authenticated/app/sales/orders/$soId'
      path: '/orders/$soId'
      fullPath: '/app/sales/orders/$soId'
      preLoaderRoute: typeof AuthenticatedAppSalesOrdersSoIdRouteImport
      parentRoute: typeof AuthenticatedAppSalesRoute
    }
    '/_authenticated/app/purchasing/orders/$poId': {
      id: '/_authenticated/app/purchasing/orders/$poId'
      path: '/orders/$poId'
      fullPath: '/app/purchasing/orders/$poId'
      preLoaderRoute: typeof AuthenticatedAppPurchasingOrdersPoIdRouteImport
      parentRoute: typeof AuthenticatedAppPurchasingRoute
    }
  }
}

interface AuthenticatedAppAccountingRouteChildren {
  AuthenticatedAppAccountingJournalsRoute: typeof AuthenticatedAppAccountingJournalsRoute
  AuthenticatedAppAccountingReportsRoute: typeof AuthenticatedAppAccountingReportsRoute
  AuthenticatedAppAccountingIndexRoute: typeof AuthenticatedAppAccountingIndexRoute
}

const AuthenticatedAppAccountingRouteChildren: AuthenticatedAppAccountingRouteChildren =
  {
    AuthenticatedAppAccountingJournalsRoute:
      AuthenticatedAppAccountingJournalsRoute,
    AuthenticatedAppAccountingReportsRoute:
      AuthenticatedAppAccountingReportsRoute,
    AuthenticatedAppAccountingIndexRoute: AuthenticatedAppAccountingIndexRoute,
  }

const AuthenticatedAppAccountingRouteWithChildren =
  AuthenticatedAppAccountingRoute._addFileChildren(
    AuthenticatedAppAccountingRouteChildren,
  )

interface AuthenticatedAppCmsRouteChildren {
  AuthenticatedAppCmsPostsRoute: typeof AuthenticatedAppCmsPostsRoute
  AuthenticatedAppCmsIndexRoute: typeof AuthenticatedAppCmsIndexRoute
}

const AuthenticatedAppCmsRouteChildren: AuthenticatedAppCmsRouteChildren = {
  AuthenticatedAppCmsPostsRoute: AuthenticatedAppCmsPostsRoute,
  AuthenticatedAppCmsIndexRoute: AuthenticatedAppCmsIndexRoute,
}

const AuthenticatedAppCmsRouteWithChildren =
  AuthenticatedAppCmsRoute._addFileChildren(AuthenticatedAppCmsRouteChildren)

interface AuthenticatedAppCrmRouteChildren {
  AuthenticatedAppCrmActivitiesRoute: typeof AuthenticatedAppCrmActivitiesRoute
  AuthenticatedAppCrmCustomersRoute: typeof AuthenticatedAppCrmCustomersRoute
  AuthenticatedAppCrmLeadsRoute: typeof AuthenticatedAppCrmLeadsRoute
  AuthenticatedAppCrmOpportunitiesRoute: typeof AuthenticatedAppCrmOpportunitiesRoute
}

const AuthenticatedAppCrmRouteChildren: AuthenticatedAppCrmRouteChildren = {
  AuthenticatedAppCrmActivitiesRoute: AuthenticatedAppCrmActivitiesRoute,
  AuthenticatedAppCrmCustomersRoute: AuthenticatedAppCrmCustomersRoute,
  AuthenticatedAppCrmLeadsRoute: AuthenticatedAppCrmLeadsRoute,
  AuthenticatedAppCrmOpportunitiesRoute: AuthenticatedAppCrmOpportunitiesRoute,
}

const AuthenticatedAppCrmRouteWithChildren =
  AuthenticatedAppCrmRoute._addFileChildren(AuthenticatedAppCrmRouteChildren)

interface AuthenticatedAppHrRouteChildren {
  AuthenticatedAppHrAttendanceRoute: typeof AuthenticatedAppHrAttendanceRoute
  AuthenticatedAppHrDepartmentsRoute: typeof AuthenticatedAppHrDepartmentsRoute
  AuthenticatedAppHrEmployeesRoute: typeof AuthenticatedAppHrEmployeesRoute
  AuthenticatedAppHrLeaveRoute: typeof AuthenticatedAppHrLeaveRoute
  AuthenticatedAppHrPayrollRoute: typeof AuthenticatedAppHrPayrollRoute
  AuthenticatedAppHrIndexRoute: typeof AuthenticatedAppHrIndexRoute
}

const AuthenticatedAppHrRouteChildren: AuthenticatedAppHrRouteChildren = {
  AuthenticatedAppHrAttendanceRoute: AuthenticatedAppHrAttendanceRoute,
  AuthenticatedAppHrDepartmentsRoute: AuthenticatedAppHrDepartmentsRoute,
  AuthenticatedAppHrEmployeesRoute: AuthenticatedAppHrEmployeesRoute,
  AuthenticatedAppHrLeaveRoute: AuthenticatedAppHrLeaveRoute,
  AuthenticatedAppHrPayrollRoute: AuthenticatedAppHrPayrollRoute,
  AuthenticatedAppHrIndexRoute: AuthenticatedAppHrIndexRoute,
}

const AuthenticatedAppHrRouteWithChildren =
  AuthenticatedAppHrRoute._addFileChildren(AuthenticatedAppHrRouteChildren)

interface AuthenticatedAppInventoryRouteChildren {
  AuthenticatedAppInventoryMovementsRoute: typeof AuthenticatedAppInventoryMovementsRoute
  AuthenticatedAppInventoryOpnameRoute: typeof AuthenticatedAppInventoryOpnameRoute
  AuthenticatedAppInventoryIndexRoute: typeof AuthenticatedAppInventoryIndexRoute
}

const AuthenticatedAppInventoryRouteChildren: AuthenticatedAppInventoryRouteChildren =
  {
    AuthenticatedAppInventoryMovementsRoute:
      AuthenticatedAppInventoryMovementsRoute,
    AuthenticatedAppInventoryOpnameRoute: AuthenticatedAppInventoryOpnameRoute,
    AuthenticatedAppInventoryIndexRoute: AuthenticatedAppInventoryIndexRoute,
  }

const AuthenticatedAppInventoryRouteWithChildren =
  AuthenticatedAppInventoryRoute._addFileChildren(
    AuthenticatedAppInventoryRouteChildren,
  )

interface AuthenticatedAppManufacturingRouteChildren {
  AuthenticatedAppManufacturingBomRoute: typeof AuthenticatedAppManufacturingBomRoute
  AuthenticatedAppManufacturingMrpRoute: typeof AuthenticatedAppManufacturingMrpRoute
  AuthenticatedAppManufacturingWoRoute: typeof AuthenticatedAppManufacturingWoRoute
  AuthenticatedAppManufacturingIndexRoute: typeof AuthenticatedAppManufacturingIndexRoute
}

const AuthenticatedAppManufacturingRouteChildren: AuthenticatedAppManufacturingRouteChildren =
  {
    AuthenticatedAppManufacturingBomRoute:
      AuthenticatedAppManufacturingBomRoute,
    AuthenticatedAppManufacturingMrpRoute:
      AuthenticatedAppManufacturingMrpRoute,
    AuthenticatedAppManufacturingWoRoute: AuthenticatedAppManufacturingWoRoute,
    AuthenticatedAppManufacturingIndexRoute:
      AuthenticatedAppManufacturingIndexRoute,
  }

const AuthenticatedAppManufacturingRouteWithChildren =
  AuthenticatedAppManufacturingRoute._addFileChildren(
    AuthenticatedAppManufacturingRouteChildren,
  )

interface AuthenticatedAppPosRouteChildren {
  AuthenticatedAppPosHistoryRoute: typeof AuthenticatedAppPosHistoryRoute
  AuthenticatedAppPosIndexRoute: typeof AuthenticatedAppPosIndexRoute
}

const AuthenticatedAppPosRouteChildren: AuthenticatedAppPosRouteChildren = {
  AuthenticatedAppPosHistoryRoute: AuthenticatedAppPosHistoryRoute,
  AuthenticatedAppPosIndexRoute: AuthenticatedAppPosIndexRoute,
}

const AuthenticatedAppPosRouteWithChildren =
  AuthenticatedAppPosRoute._addFileChildren(AuthenticatedAppPosRouteChildren)

interface AuthenticatedAppPurchasingRouteChildren {
  AuthenticatedAppPurchasingSuppliersRoute: typeof AuthenticatedAppPurchasingSuppliersRoute
  AuthenticatedAppPurchasingIndexRoute: typeof AuthenticatedAppPurchasingIndexRoute
  AuthenticatedAppPurchasingOrdersPoIdRoute: typeof AuthenticatedAppPurchasingOrdersPoIdRoute
}

const AuthenticatedAppPurchasingRouteChildren: AuthenticatedAppPurchasingRouteChildren =
  {
    AuthenticatedAppPurchasingSuppliersRoute:
      AuthenticatedAppPurchasingSuppliersRoute,
    AuthenticatedAppPurchasingIndexRoute: AuthenticatedAppPurchasingIndexRoute,
    AuthenticatedAppPurchasingOrdersPoIdRoute:
      AuthenticatedAppPurchasingOrdersPoIdRoute,
  }

const AuthenticatedAppPurchasingRouteWithChildren =
  AuthenticatedAppPurchasingRoute._addFileChildren(
    AuthenticatedAppPurchasingRouteChildren,
  )

interface AuthenticatedAppSalesRouteChildren {
  AuthenticatedAppSalesCustomersRoute: typeof AuthenticatedAppSalesCustomersRoute
  AuthenticatedAppSalesInvoicesRoute: typeof AuthenticatedAppSalesInvoicesRoute
  AuthenticatedAppSalesIndexRoute: typeof AuthenticatedAppSalesIndexRoute
  AuthenticatedAppSalesOrdersSoIdRoute: typeof AuthenticatedAppSalesOrdersSoIdRoute
}

const AuthenticatedAppSalesRouteChildren: AuthenticatedAppSalesRouteChildren = {
  AuthenticatedAppSalesCustomersRoute: AuthenticatedAppSalesCustomersRoute,
  AuthenticatedAppSalesInvoicesRoute: AuthenticatedAppSalesInvoicesRoute,
  AuthenticatedAppSalesIndexRoute: AuthenticatedAppSalesIndexRoute,
  AuthenticatedAppSalesOrdersSoIdRoute: AuthenticatedAppSalesOrdersSoIdRoute,
}

const AuthenticatedAppSalesRouteWithChildren =
  AuthenticatedAppSalesRoute._addFileChildren(
    AuthenticatedAppSalesRouteChildren,
  )

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAccountingRoute: typeof AuthenticatedAppAccountingRouteWithChildren
  AuthenticatedAppCmsRoute: typeof AuthenticatedAppCmsRouteWithChildren
  AuthenticatedAppCrmRoute: typeof AuthenticatedAppCrmRouteWithChildren
  AuthenticatedAppHrRoute: typeof AuthenticatedAppHrRouteWithChildren
  AuthenticatedAppInventoryRoute: typeof AuthenticatedAppInventoryRouteWithChildren
  AuthenticatedAppManufacturingRoute: typeof AuthenticatedAppManufacturingRouteWithChildren
  AuthenticatedAppPosRoute: typeof AuthenticatedAppPosRouteWithChildren
  AuthenticatedAppPurchasingRoute: typeof AuthenticatedAppPurchasingRouteWithChildren
  AuthenticatedAppSalesRoute: typeof AuthenticatedAppSalesRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppCategoriesIndexRoute: typeof AuthenticatedAppCategoriesIndexRoute
  AuthenticatedAppProductsIndexRoute: typeof AuthenticatedAppProductsIndexRoute
  AuthenticatedAppUnitsIndexRoute: typeof AuthenticatedAppUnitsIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAccountingRoute: AuthenticatedAppAccountingRouteWithChildren,
  AuthenticatedAppCmsRoute: AuthenticatedAppCmsRouteWithChildren,
  AuthenticatedAppCrmRoute: AuthenticatedAppCrmRouteWithChildren,
  AuthenticatedAppHrRoute: AuthenticatedAppHrRouteWithChildren,
  AuthenticatedAppInventoryRoute: AuthenticatedAppInventoryRouteWithChildren,
  AuthenticatedAppManufacturingRoute:
    AuthenticatedAppManufacturingRouteWithChildren,
  AuthenticatedAppPosRoute: AuthenticatedAppPosRouteWithChildren,
  AuthenticatedAppPurchasingRoute: AuthenticatedAppPurchasingRouteWithChildren,
  AuthenticatedAppSalesRoute: AuthenticatedAppSalesRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppCategoriesIndexRoute: AuthenticatedAppCategoriesIndexRoute,
  AuthenticatedAppProductsIndexRoute: AuthenticatedAppProductsIndexRoute,
  AuthenticatedAppUnitsIndexRoute: AuthenticatedAppUnitsIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
